export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_USER_CHECK_STATE = "AUTH_USER_CHECK_STATE";

export const ACCOUNTS_START = "ACCOUNTS_START";
export const ACCOUNTS_SUCCESS = "ACCOUNTS_SUCCESS";
export const ACCOUNTS_FAIL = "ACCOUNTS_FAIL";

export const ACCOUNTS = "ACCOUNTS";
export const DELETE_ACCOUNTS = "DELETE_ACCOUNTS";
export const LOGOUT_ACCOUNTS = "LOGOUT_ACCOUNTS";
export const CHANGE_ACCOUNTS_ATTRIBUTES = "CHANGE_ACCOUNTS_ATTRIBUTES";

export const TASKS_LIST = "TASKS_LIST";
export const TASKS_LIST_START = "TASKS_LIST_START";
export const SAVE_TASKS_LIST = "SAVE_TASKS_LIST";
